export enum Purpose {
  RESET_PASSWORD = 'RESET_PASSWORD',
  CREATE_ACCOUNT = 'CREATE_ACCOUNT',
  REFRESH_TOKEN = 'REFRESH_TOKEN',
  SIGN_IN = 'SIGN_IN',
  USE_OTHER_SERVICES = 'USE_OTHER_SERVICES',
}
