export enum VerificationType {
    PASSWORD_RESET = 'PASSWORD_RESET',
    EMAIL_VERIFICATION = 'EMAIL_VERIFICATION',
    ACCOUNT_CREATION = 'ACCOUNT_CREATION',
    PHONE_VERIFICATION = 'PHONE_VERIFICATION',
}