// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxU4cVFzjW-fyxVYnDNISxFmweTbAKNf0',
    appId: '1:809425891688:web:4d381d0f99f9f9aaa5a6dd',
    messagingSenderId: '809425891688',
    projectId: 'floodhelper-374c0',
    authDomain: 'floodhelper-374c0.firebaseapp.com',
    storageBucket: 'floodhelper-374c0.firebasestorage.app',
    measurementId: 'G-3RWYCP4Y73',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPxiAAq68u5voQx7i8gSAnT5jkDxM2uAs',
    appId: '1:809425891688:android:47d08944284c7939a5a6dd',
    messagingSenderId: '809425891688',
    projectId: 'floodhelper-374c0',
    storageBucket: 'floodhelper-374c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUG1sg5ZMIFypfcP_rlvpeRg05aYy32Ys',
    appId: '1:809425891688:ios:a35e72defba24802a5a6dd',
    messagingSenderId: '809425891688',
    projectId: 'floodhelper-374c0',
    storageBucket: 'floodhelper-374c0.firebasestorage.app',
    iosBundleId: 'com.example.antiflood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUG1sg5ZMIFypfcP_rlvpeRg05aYy32Ys',
    appId: '1:809425891688:ios:a35e72defba24802a5a6dd',
    messagingSenderId: '809425891688',
    projectId: 'floodhelper-374c0',
    storageBucket: 'floodhelper-374c0.firebasestorage.app',
    iosBundleId: 'com.example.antiflood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxU4cVFzjW-fyxVYnDNISxFmweTbAKNf0',
    appId: '1:809425891688:web:0925274cb93bbd56a5a6dd',
    messagingSenderId: '809425891688',
    projectId: 'floodhelper-374c0',
    authDomain: 'floodhelper-374c0.firebaseapp.com',
    storageBucket: 'floodhelper-374c0.firebasestorage.app',
    measurementId: 'G-M20T24YCXS',
  );
}
